# Generated by Django 3.1.3 on 2021-01-15 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='thumbnail',
            field=models.ImageField(upload_to='static/img/'),
        ),
    ]
